export interface SearchPostDto {
  id: string;
  dateCreated: string;
  dateUpdated?: string | null;
  deleted: string;
  caption?: string;
  cleanedCaption: string;
  createdTime?: number | null;
  sidecarMedias?: any;
  likesCount?: number;
  viewsCount?: number;
  vendorContact?: any;
  biography?: string;
  accountName?: string;
  vendorId: string;
  profilePicture?: string;
  make?: string;
  model?: string;
  variant?: string;
  registration?: number;
  mileage?: number;
  price?: number;
  transmission?: string;
  fuelType?: string;
  engineSize?: number;
  drivetrain?: string;
  seats?: number;
  numberOfDoors?: number;
  bodyType?: string;
  emissionGroup?: string;
  contact?: any;
  customsPaid?: boolean;
  options?: any;
  sold?: boolean;
  type?: string;
  promotionTo?: number;
  highlightedTo?: number;
  renewTo?: number;
  renewInterval?: string;
  renewedTime?: number;
  mostWantedTo?: number;
  minPrice?: number;
  maxPrice?: number;
  canExchange?: boolean;
}
