export type LegacyRoute = {
  method: string;
  path: string;
  summary: string;
  security?: boolean;
};

export const legacyRoutes: LegacyRoute[] = [
  {
    method: 'post',
    path: '/authentication/login',
    summary: 'Authenticate user (legacy)',
  },
  {
    method: 'post',
    path: '/user/login',
    summary: 'Authenticate user (legacy user path)',
  },
  { method: 'post', path: '/user/create-user', summary: 'Create user account' },
  { method: 'get', path: '/user/refresh-token', summary: 'Refresh token' },
  {
    method: 'post',
    path: '/user/reset-password',
    summary: 'Request password reset',
  },
  {
    method: 'post',
    path: '/user/verify-password',
    summary: 'Confirm password reset',
  },
  {
    method: 'get',
    path: '/instagram-sync/get-access-token',
    summary: 'Exchange Instagram code',
  },
  { method: 'post', path: '/car-details/search', summary: 'Search listings' },
  {
    method: 'post',
    path: '/car-details/price-calculate',
    summary: 'Calculate price insights',
  },
  {
    method: 'get',
    path: '/car-details/most-wanted',
    summary: 'Most wanted listings',
  },
  {
    method: 'post',
    path: '/car-details/result-count',
    summary: 'Search result count',
  },
  { method: 'get', path: '/car-details/post/{id}', summary: 'Listing details' },
  {
    method: 'get',
    path: '/car-details/post/caption/{id}',
    summary: 'Listing caption',
  },
  {
    method: 'get',
    path: '/car-details/related-post/{id}',
    summary: 'Related listings by post id',
  },
  {
    method: 'post',
    path: '/car-details/related-post-filter',
    summary: 'Related listings by filter',
  },
  { method: 'get', path: '/sitemap/data', summary: 'Default sitemap payload' },
  {
    method: 'get',
    path: '/sitemap/get-sitemap/{appName}',
    summary: 'Sitemap payload by app',
  },
  { method: 'get', path: '/data/makes', summary: 'Car makes' },
  { method: 'get', path: '/data/models/{make}', summary: 'Car models by make' },
  {
    method: 'get',
    path: '/data/makes/motorcycles',
    summary: 'Motorcycle makes',
  },
  {
    method: 'get',
    path: '/data/models/motorcycles/{make}',
    summary: 'Motorcycle models by make',
  },
  {
    method: 'get',
    path: '/data/vendors/{name}',
    summary: 'Vendor profile by name',
  },
  {
    method: 'get',
    path: '/data/vendors/biography/{name}',
    summary: 'Vendor biography by name',
  },
  {
    method: 'get',
    path: '/data/article/{lang}/{id}',
    summary: 'Single article',
  },
  {
    method: 'get',
    path: '/data/articles/{lang}/{id}',
    summary: 'Article list by category',
  },
  {
    method: 'get',
    path: '/data/articles/{lang}/{id}/total',
    summary: 'Article total pages',
  },
  {
    method: 'get',
    path: '/data/latest/articles/{lang}',
    summary: 'Latest articles',
  },
  {
    method: 'get',
    path: '/data/related/articles/{lang}/{category}',
    summary: 'Related articles',
  },
  {
    method: 'get',
    path: '/data/metadata/articles/{lang}/{id}',
    summary: 'Article metadata',
  },
  { method: 'post', path: '/data/create-post', summary: 'Create post' },
  { method: 'post', path: '/data/update-post', summary: 'Update post' },
  {
    method: 'post',
    path: '/data/create-user-post',
    summary: 'Create user and post',
  },
  { method: 'post', path: '/data/upload-image', summary: 'Upload image' },
  {
    method: 'get',
    path: '/favourites/check',
    summary: 'Check favourites list',
  },
  { method: 'get', path: '/favourites/get', summary: 'Get favourites list' },
  {
    method: 'get',
    path: '/admin/posts',
    summary: 'Admin posts list',
    security: true,
  },
  {
    method: 'get',
    path: '/admin/posts/{id}',
    summary: 'Admin post by id',
    security: true,
  },
  {
    method: 'get',
    path: '/admin/posts/delete/{id}',
    summary: 'Delete post',
    security: true,
  },
  {
    method: 'get',
    path: '/admin/posts/sold/{id}',
    summary: 'Mark post sold',
    security: true,
  },
  {
    method: 'get',
    path: '/admin/user',
    summary: 'Current admin user',
    security: true,
  },
  {
    method: 'post',
    path: '/admin/user',
    summary: 'Edit admin user (deferred proxy)',
    security: true,
  },
  {
    method: 'post',
    path: '/admin/user/change-password',
    summary: 'Change password (deferred proxy)',
    security: true,
  },
  {
    method: 'post',
    path: '/admin/vendor/contact',
    summary: 'Update vendor contact (deferred proxy)',
    security: true,
  },
  {
    method: 'post',
    path: '/admin/vendor/biography',
    summary: 'Update vendor biography (deferred proxy)',
    security: true,
  },
  {
    method: 'post',
    path: '/admin/vendor/profile-picture',
    summary: 'Update vendor profile picture (deferred proxy)',
    security: true,
  },
  { method: 'post', path: '/api/v1/orders', summary: 'Create payment order' },
  {
    method: 'post',
    path: '/api/v1/orders/{orderID}/capture',
    summary: 'Capture payment order',
  },
  {
    method: 'get',
    path: '/authentication/login-with-code',
    summary: 'Admin login with code',
  },
  {
    method: 'get',
    path: '/role-management',
    summary: 'Role list',
    security: true,
  },
  {
    method: 'post',
    path: '/role-management/create-role',
    summary: 'Create role',
    security: true,
  },
  {
    method: 'post',
    path: '/role-management/update-role/{id}',
    summary: 'Update role',
    security: true,
  },
  {
    method: 'delete',
    path: '/role-management/delete-role/{id}',
    summary: 'Delete role',
    security: true,
  },
  {
    method: 'get',
    path: '/role-management/role/{id}',
    summary: 'Get role by id',
    security: true,
  },
  {
    method: 'get',
    path: '/user-management',
    summary: 'User list',
    security: true,
  },
  {
    method: 'post',
    path: '/user-management/create-user',
    summary: 'Create user',
    security: true,
  },
  {
    method: 'post',
    path: '/user-management/update-user/{id}',
    summary: 'Update user',
    security: true,
  },
  {
    method: 'delete',
    path: '/user-management/delete-user/{id}',
    summary: 'Delete user',
    security: true,
  },
  {
    method: 'get',
    path: '/user-management/user/{id}',
    summary: 'Get user by id',
    security: true,
  },
  {
    method: 'get',
    path: '/user-management/user/username/{username}',
    summary: 'Get user by username',
    security: true,
  },
  {
    method: 'post',
    path: '/vendor/update',
    summary: 'Admin vendor update',
    security: true,
  },
  {
    method: 'delete',
    path: '/vendor/delete/{id}',
    summary: 'Admin vendor delete',
    security: true,
  },
  {
    method: 'post',
    path: '/post/save-post',
    summary: 'Save post (AP tooling)',
  },
  {
    method: 'get',
    path: '/post/posts',
    summary: 'Get posts by ids (AP tooling)',
  },
  {
    method: 'post',
    path: '/post/update/{id}',
    summary: 'Update post (AP tooling)',
  },
  { method: 'get', path: '/post/scrape-posts', summary: 'Start scraping run' },
  {
    method: 'get',
    path: '/post/scrape-posts/create',
    summary: 'Create scrape status',
  },
  {
    method: 'get',
    path: '/post/scrape-posts/details',
    summary: 'Read scrape status',
  },
  {
    method: 'post',
    path: '/post/scrape-posts/update',
    summary: 'Update scrape status',
  },
  {
    method: 'get',
    path: '/post/scrape-posts/cleanPosts',
    summary: 'Clean posts job',
  },
  {
    method: 'get',
    path: '/post/scrape-posts/update-search',
    summary: 'Move posts to search',
  },
  {
    method: 'get',
    path: '/post/scrape-posts/fix-details',
    summary: 'Fix post details',
  },
  { method: 'get', path: '/post/get-most-liked', summary: 'Most liked posts' },
  { method: 'get', path: '/post/auto-renew', summary: 'Auto renew posts' },
  {
    method: 'get',
    path: '/vendor-management/all',
    summary: 'Vendor list (AP)',
  },
  {
    method: 'post',
    path: '/vendor-management/add/{id}',
    summary: 'Add vendor (AP)',
  },
  {
    method: 'post',
    path: '/vendor-management/add/details/{id}',
    summary: 'Add vendor details (AP)',
  },
  {
    method: 'post',
    path: '/vendor-management/edit/{id}',
    summary: 'Edit vendor (AP)',
  },
  {
    method: 'get',
    path: '/vendor-management/next-to-crawl',
    summary: 'Next vendor to crawl',
  },
  {
    method: 'get',
    path: '/vendor-management/mark-vendor-for-crawl-next/{id}',
    summary: 'Mark vendor crawl next',
  },
  {
    method: 'get',
    path: '/vendor-management/toggle-deleted/{id}',
    summary: 'Toggle vendor deleted',
  },
  {
    method: 'get',
    path: '/car-details/generate-prompt',
    summary: 'Generate detail prompt',
  },
  {
    method: 'get',
    path: '/car-details/generate-prompt-fix-variant',
    summary: 'Generate variant prompt',
  },
  {
    method: 'get',
    path: '/car-details/generate-prompt-fix-registration',
    summary: 'Generate registration prompt',
  },
  {
    method: 'get',
    path: '/car-details/generate-prompt-fix-mileage',
    summary: 'Generate mileage prompt',
  },
  {
    method: 'get',
    path: '/car-details/generate-prompt-fix-price',
    summary: 'Generate price prompt',
  },
  {
    method: 'get',
    path: '/car-details/generate-prompt-fix-motorcycle-details',
    summary: 'Generate motorcycle prompt',
  },
  {
    method: 'get',
    path: '/car-details/get-manual-draft-posts',
    summary: 'Manual draft posts',
  },
  {
    method: 'post',
    path: '/car-details/import',
    summary: 'Import detail prompt result',
  },
  { method: 'get', path: '/car-details/clean-cache', summary: 'Clean cache' },
  { method: 'get', path: '/make-model-data/makes', summary: 'Make list (AP)' },
  {
    method: 'get',
    path: '/make-model-data/models/{make}',
    summary: 'Model list by make (AP)',
  },
  {
    method: 'get',
    path: '/make-model-data/makes/motorcycle',
    summary: 'Motorcycle make list (AP)',
  },
  {
    method: 'get',
    path: '/make-model-data/models/motorcycle/{make}',
    summary: 'Motorcycle model list by make (AP)',
  },
  { method: 'get', path: '/article/all', summary: 'Article list (AP)' },
  { method: 'post', path: '/article/create', summary: 'Article create (AP)' },
  {
    method: 'post',
    path: '/article/update/{id}',
    summary: 'Article update (AP)',
  },
  { method: 'get', path: '/article/{id}', summary: 'Article read (AP)' },
  {
    method: 'get',
    path: '/sitemap/generate',
    summary: 'Generate sitemap (AP)',
  },
  {
    method: 'get',
    path: '/api/v1/orders/send-remind-emails',
    summary: 'Send near-expiry reminders',
  },
];
